author: Dazzel
database: false
main: com.dazzel.spiritblocks.SpiritBlocks
name: SpiritBlocks
startup: postworld
version: '0.6'
discription: Let you select some blocks where you place your 'spirit'.
commands:
  spirit:
    description: Place a spirit
    usage: For help type /<command> help
    aliases: [spiritset,spirits]
  shrine:
    description: Place a shrine
    usage: For help type /<command> help
permissions:
  spirit.create:
    default: false
    description: Create a spirit
  spirit.delete:
    default: false
    description: Delete a spirit
  spirit.respawn:
    default: false
    description: Respawn at a spiritlocation    
  shrine.*: 
    description: Gives all shrine options
    children:
      shrine.create: true
      shrine.delete: true
  shrine.create:
    default: op
    description: Create a shrine
  shrine.delete:
    default: op
    description: Delete a shrine    
